### ISSUE TITLE
Failed creating OpenGL window.

### ISSUE THREAD

**Issue by christian-rauch** [isl-org/Open3D#7162]
### Checklist

- [x] I have searched for [similar issues](https://github.com/isl-org/Open3D/issues).
- [x] For Python issues, I have tested with the [latest development wheel](https://www.open3d.org/docs/latest/getting_started.html#development-version-pip).
- [x] I have checked the [release documentation](https://www.open3d.org/docs/release/) and the [latest documentation](https://www.open3d.org/docs/latest/) (for `main` branch).

### Describe the issue

I am trying to visualise a geometry on an Ubuntu 24.04 desktop via `draw_geometries` but the program crashes with `Failed creating OpenGL window.`.

Similar issues on other configurations:
- https://github.com/isl-org/Open3D/issues/5126
- https://github.com/isl-org/Open3D/issues/6072

### Steps to reproduce the bug

```python
import open3d as o3d
o3d.visualization.draw_geometries([o3d.geometry.TriangleMesh.create_coordinate_frame()])
```

### Error message

```
[Open3D WARNING] GLFW Error: Wayland: The platform does not support setting the window position
[Open3D WARNING] Failed to initialize GLEW.
[Open3D WARNING] [DrawGeometries] Failed creating OpenGL window.
```

### Expected behavior

A window should be shown.

### Open3D, Python and System information

```markdown
- Operating system: Ubuntu 24.04
- Python version: ´3.12.3 (main, Jan 17 2025, 18:03:48) [GCC 13.3.0]´
- Open3D version: ´0.19.0´
- System architecture: x86
- Is this a remote workstation?: no
- How did you install Open3D?: pip
```

### Additional information

I am using the "Intel Arc Graphics" GPU on Wayland (Ubuntu 24.04 default).

`inxi -G`:
```
Graphics:
  Device-1: Intel Meteor Lake-P [Intel Arc Graphics] driver: i915 v: kernel
  Device-2: Luxvisions Innotech Integrated Camera driver: uvcvideo type: USB
  Display: wayland server: X.Org v: 23.2.6 with: Xwayland v: 23.2.6
    compositor: gnome-shell v: 46.0 driver: dri: iris gpu: i915
    resolution: 3072x1728~60Hz
  API: EGL v: 1.5 drivers: iris,swrast
    platforms: gbm,wayland,x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel v: N/A renderer: Mesa
    Intel Arc Graphics (MTL)
```
